FROM nginx:latest

# Production config
COPY nginx/                        /etc/nginx/

# Test setup

COPY tests/nginx                      /etc/nginx/
COPY tests/ssl/nginx-selfsigned.crt   /etc/ssl/certs/nginx-selfsigned.crt
COPY tests/ssl/nginx-selfsigned.key   /etc/ssl/private/nginx-selfsigned.key

STOPSIGNAL SIGQUIT
