FROM nginx:latest

# Test setup
COPY nginx                      /etc/nginx/
COPY ssl/nginx-selfsigned.crt   /etc/ssl/certs/nginx-selfsigned.crt
COPY ssl/nginx-selfsigned.key   /etc/ssl/private/nginx-selfsigned.key
